### ISSUE TITLE
The example is OK but how about some docs? 

### ISSUE THREAD

**Issue by ScottyMac52** [danielchalmers/WpfAboutView#1]
I honestly have no idea where to start to get your About Dialog to work in my application so I am moving on to other alternatives. Some docs for those of us that are experienced devs but fairly new to WPF would be nice. ;-)

**Comment by danielchalmers** [comment]
haha yeah, it's definitely not obvious how to use it. I made it for a few of my own apps without much intention of building on it, but I figured I could put it on here in case someone might find it useful/interesting enough as is.

Here's an example of it in use: https://github.com/danielchalmers/DesktopClock/blob/31cec1ddf5276267b8bce0364e1bff50519e9c10/DesktopClock/MainWindow.xaml.cs#L27-L83

**Comment by danielchalmers** [comment]
there's now a brief example on the README, and samples in the ExampleApp
